// Generated by CoffeeScript 1.6.3
(function() {
  module.exports = function(grunt) {
    grunt.initConfig({
      coffee: {
        build: {
          files: [
            {
              expand: true,
              cwd: 'master-node/lib/',
              src: ['**/*.coffee'],
              dest: 'lib/',
              ext: '.js'
            }
          ]
        }
      }
    });
    grunt.loadNpmTasks("grunt-contrib-coffee");
    return grunt.registerTask('default', 'Try Logging', function() {
      return grunt.log.write('Running the default task');
    });
  };

}).call(this);
